### ISSUE TITLE
error using mkdir

### ISSUE THREAD

**Issue by AlineXSSantos** [LiberaliLabFMI/main_settings_file_final#1]
The directory E:\gliberal\Users\dasialin\E:\gliberal\Users\dasialin\160810-AS-160810AS042_20160810_121027_3D\ is being processed ...
Error using mkdir
The filename, directory name, or volume label syntax is incorrect.

Error in main_settings_file_final (line 68)
    mkdir(reports_folder)

**Comment by SaadiaIftikhar** [comment]
The directory **E:\gliberal\Users\dasialin**\E:\gliberal\Users\dasialin\160810-AS-160810AS042_20160810_121027_3D\

Marked **BOLD** is an extra bit in your setting script ... If you correct that, you will not get this error again!
